// Generated by npm run db:types. Do not edit manually.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  graphql_public: {
    Tables: {
      [_ in never]: never;
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      graphql: {
        Args: {
          extensions?: Json;
          operationName?: string;
          query?: string;
          variables?: Json;
        };
        Returns: Json;
      };
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
  public: {
    Tables: {
      planning_center_plan_items: {
        Row: {
          created_at: string;
          description: string;
          element_key: string;
          html_details: string;
          id: string;
          item_type: string;
          liturgical_movement: string;
          plan_id: string;
          planning_center_id: string;
          planning_center_updated_at: string | null;
          raw_section_title: string | null;
          sequence: number;
          service_position: string | null;
          title: string;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          description?: string;
          element_key: string;
          html_details?: string;
          id?: string;
          item_type: string;
          liturgical_movement: string;
          plan_id: string;
          planning_center_id: string;
          planning_center_updated_at?: string | null;
          raw_section_title?: string | null;
          sequence: number;
          service_position?: string | null;
          title: string;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          description?: string;
          element_key?: string;
          html_details?: string;
          id?: string;
          item_type?: string;
          liturgical_movement?: string;
          plan_id?: string;
          planning_center_id?: string;
          planning_center_updated_at?: string | null;
          raw_section_title?: string | null;
          sequence?: number;
          service_position?: string | null;
          title?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "planning_center_plan_items_plan_id_fkey";
            columns: ["plan_id"];
            isOneToOne: false;
            referencedRelation: "planning_center_plans";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "planning_center_plan_items_plan_id_fkey";
            columns: ["plan_id"];
            isOneToOne: false;
            referencedRelation: "scripture_usage_rows";
            referencedColumns: ["plan_id"];
          },
        ];
      };
      planning_center_plans: {
        Row: {
          created_at: string;
          display_dates: string | null;
          id: string;
          planning_center_id: string;
          planning_center_updated_at: string | null;
          planning_center_url: string | null;
          series_title: string | null;
          service_date: string;
          service_type_id: string;
          title: string;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          display_dates?: string | null;
          id?: string;
          planning_center_id: string;
          planning_center_updated_at?: string | null;
          planning_center_url?: string | null;
          series_title?: string | null;
          service_date: string;
          service_type_id: string;
          title: string;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          display_dates?: string | null;
          id?: string;
          planning_center_id?: string;
          planning_center_updated_at?: string | null;
          planning_center_url?: string | null;
          series_title?: string | null;
          service_date?: string;
          service_type_id?: string;
          title?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "planning_center_plans_service_type_id_fkey";
            columns: ["service_type_id"];
            isOneToOne: false;
            referencedRelation: "planning_center_service_types";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "planning_center_plans_service_type_id_fkey";
            columns: ["service_type_id"];
            isOneToOne: false;
            referencedRelation: "scripture_usage_rows";
            referencedColumns: ["service_type_id"];
          },
        ];
      };
      planning_center_service_types: {
        Row: {
          archived_at: string | null;
          created_at: string;
          id: string;
          name: string;
          planning_center_id: string;
          planning_center_updated_at: string | null;
          updated_at: string;
        };
        Insert: {
          archived_at?: string | null;
          created_at?: string;
          id?: string;
          name: string;
          planning_center_id: string;
          planning_center_updated_at?: string | null;
          updated_at?: string;
        };
        Update: {
          archived_at?: string | null;
          created_at?: string;
          id?: string;
          name?: string;
          planning_center_id?: string;
          planning_center_updated_at?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      scripture_chapter_usages: {
        Row: {
          book: string;
          chapter: number;
          scripture_reference_id: string;
        };
        Insert: {
          book: string;
          chapter: number;
          scripture_reference_id: string;
        };
        Update: {
          book?: string;
          chapter?: number;
          scripture_reference_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "scripture_chapter_usages_scripture_reference_id_fkey";
            columns: ["scripture_reference_id"];
            isOneToOne: false;
            referencedRelation: "scripture_references";
            referencedColumns: ["id"];
          },
        ];
      };
      scripture_references: {
        Row: {
          canonical_reference: string;
          created_at: string;
          end_book: string;
          end_chapter: number;
          end_verse: number | null;
          id: string;
          plan_item_id: string;
          provenance: Json;
          raw_reference: string;
          source_field: string;
          start_book: string;
          start_chapter: number;
          start_verse: number | null;
        };
        Insert: {
          canonical_reference: string;
          created_at?: string;
          end_book: string;
          end_chapter: number;
          end_verse?: number | null;
          id?: string;
          plan_item_id: string;
          provenance?: Json;
          raw_reference: string;
          source_field: string;
          start_book: string;
          start_chapter: number;
          start_verse?: number | null;
        };
        Update: {
          canonical_reference?: string;
          created_at?: string;
          end_book?: string;
          end_chapter?: number;
          end_verse?: number | null;
          id?: string;
          plan_item_id?: string;
          provenance?: Json;
          raw_reference?: string;
          source_field?: string;
          start_book?: string;
          start_chapter?: number;
          start_verse?: number | null;
        };
        Relationships: [
          {
            foreignKeyName: "scripture_references_plan_item_id_fkey";
            columns: ["plan_item_id"];
            isOneToOne: false;
            referencedRelation: "planning_center_plan_items";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "scripture_references_plan_item_id_fkey";
            columns: ["plan_item_id"];
            isOneToOne: false;
            referencedRelation: "scripture_usage_rows";
            referencedColumns: ["item_id"];
          },
        ];
      };
      sync_runs: {
        Row: {
          completed_at: string | null;
          error_message: string | null;
          heartbeat_at: string;
          id: string;
          items_processed: number;
          kind: string;
          plans_processed: number;
          scripture_references_found: number;
          service_types_processed: number;
          started_at: string;
          started_by: string | null;
          status: string;
          sync_end_date: string;
          sync_start_date: string;
        };
        Insert: {
          completed_at?: string | null;
          error_message?: string | null;
          heartbeat_at?: string;
          id?: string;
          items_processed?: number;
          kind?: string;
          plans_processed?: number;
          scripture_references_found?: number;
          service_types_processed?: number;
          started_at?: string;
          started_by?: string | null;
          status: string;
          sync_end_date: string;
          sync_start_date: string;
        };
        Update: {
          completed_at?: string | null;
          error_message?: string | null;
          heartbeat_at?: string;
          id?: string;
          items_processed?: number;
          kind?: string;
          plans_processed?: number;
          scripture_references_found?: number;
          service_types_processed?: number;
          started_at?: string;
          started_by?: string | null;
          status?: string;
          sync_end_date?: string;
          sync_start_date?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      scripture_usage_rows: {
        Row: {
          book: string | null;
          canonical_reference: string | null;
          chapter: number | null;
          element_key: string | null;
          element_title: string | null;
          item_id: string | null;
          liturgical_movement: string | null;
          plan_id: string | null;
          plan_title: string | null;
          planning_center_url: string | null;
          provenance: Json | null;
          raw_reference: string | null;
          raw_section_title: string | null;
          scripture_reference_id: string | null;
          sequence: number | null;
          service_date: string | null;
          service_type_id: string | null;
          service_type_name: string | null;
          source_field: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "scripture_chapter_usages_scripture_reference_id_fkey";
            columns: ["scripture_reference_id"];
            isOneToOne: false;
            referencedRelation: "scripture_references";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Functions: {
      acquire_sync: {
        Args: {
          p_end: string;
          p_kind: string;
          p_start: string;
          p_user: string;
        };
        Returns: string;
      };
      replace_plan: {
        Args: {
          p_items: Json;
          p_plan: Json;
          p_run: string;
          p_service_type: Json;
        };
        Returns: string;
      };
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">;

type DefaultSchema = DatabaseWithoutInternals[Extract<
  keyof Database,
  "public"
>];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    keyof DefaultSchema["Tables"] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    keyof DefaultSchema["Tables"] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    keyof DefaultSchema["Enums"] | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  graphql_public: {
    Enums: {},
  },
  public: {
    Enums: {},
  },
} as const;
